infiles :
  data850: analysis_maps/Sh2_61-j850_r0_contamination_mf.fits
  snr850: analysis_maps/Sh2_61-j850_r0_contamination_mf-snr.fits
  clumpdef: findclumps/Sh2-61-j850_r0_contamination_mf-fw-snr6-extr.FITS
  data450: analysis_maps/Sh2_61-j450_r0mf.fits
  snr450: analysis_maps/Sh2_61-j450_r0mf-snr.fits
#
phys_params:
  beta : 1.8
  mu: 2.8
  distance : 2500
  dtogas: 160
  #
  beam : 17.5461
  pixsize: 3

data_params:
  snr_450 : 4.0
  ini_temp : 3.0
  #
  flux_factor : 0.001
  #
  type_cutTd : 'variance'
  cut_Td : 30.
  #
  type_cutM : 'snr'
  cut_M : 2
  #
  manual_Tdust : 20.
  manual_varTdust : 30.
#
outfiles:
  ratio : analysis_maps/zcfg_ratio.fits
  temperature : analysis_maps/zcfg_temp.fits
  mass : analysis_maps/zcfg_mass.fits
  clumptable: analysis_maps/zcfg_clump_table.fits
