infiles :
  data850: analysis_maps/Sh2_61-j850r0_co_mb.fits
  snr850: analysis_maps/Sh2_61-j850r0_co_mb-snr.fits
  clumpdef: findclumps/Sh2_61-j850r0_co_mb-fw_01-clumps.fits
  data450: analysis_maps/Sh2_61-j450r0_mb-aligned_to-j850r0_co_mb.fits
  snr450: analysis_maps/Sh2_61-j450r0_mb-snr-aligned_to-j850r0_co_mb.fits

phys_params:
  beta : 1.8
  mu: 2.8
  distance : 2500
  dtogas: 160
  #
  beam : 17.5461
  pixsize: 3.

data_params:
  snr_450 : 4.0
  ini_temp : 3.0
  #
  type_cutTd : 'variance'
  cut_Td : 30.
  #
  type_cutM : 'snr'
  cut_M : 2.
  #
  manual_Tdust : 15.
  manual_varTdust : 30.

outfiles:
  ratio : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_01-ratio.fits
  temperature : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_01-tdust.fits
  mass : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_01-mass.fits
  N : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_01-N.fits
  #tau : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_01-tau.fits
  clumptable:  analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_01-clump_table.fits

output_options:
  tau_opt: thin
  #tdust: calc_only
  #mass: calc_only
  #N: calc_only
#  tdust: [all], calc_only, manual_only
#  mass: [all], calc_only, manual_only
#  N: [all], calc_only, manual_only
#  tau_opt: [thin], thick
#  tau : [all], calc_only, manual_only

