infiles :
  data850: analysis_maps/Sh2_61-j850r0_co_mb.fits
  snr850: analysis_maps/Sh2_61-j850r0_co_mb-snr.fits
  clumpdef: findclumps/Sh2_61-j850r0_co_mb-fw_02-clumps.fits
  data450: analysis_maps/Sh2_61-j450r0_mb-aligned_to-j850r0_co_mb.fits
  snr450: analysis_maps/Sh2_61-j450r0_mb-snr-aligned_to-j850r0_co_mb.fits

phys_params:
  beta : 1.8
  mu: 2.8
  distance : 2500
  dtogas: 160
  #
  beam : 17.5461
  pixsize: 3.

data_params:
  snr_450 : 4.0
  ini_temp : 3.0
  #
  type_cutTd : 'variance'
  cut_Td : 30.
  #
  type_cutM : 'snr'
  cut_M : 2
  #
  manual_Tdust : 15.
  manual_varTdust : 30.

outfiles:
  ratio : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_02_ref-ratio.fits
  temperature : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_02_ref-tdust.fits
  mass : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_02_ref-mass.fits
  N : analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_02_ref-N.fits
  clumptable: analysis_maps/Sh2_61-j850r0_co_mb__j450r0_mb-fw_02_ref-clump_table.fits

output_options:
  fill_Tdust: 'extrapolate'
  tau_opt: thin
