page:
  name: 'Sh2-61 j850r1'
  outfile: 'Sh2_61-j850r1-map.pdf'
  dpi: 100
  size: [9,9]

panels:
  yx: [1,1]
  view:
    type: 'radius'
    radius: '9.6arcmin'
    
  font: {family: 'Nimbus Roman'}

  axes:
    axes_labels:
      font: {size: 'xx-large'}

    tick_labels:
      font: {size: 'large'}
      
  labels:
    color: 'purple'
    label_A: { text: Sh2-61, relative: True,
               position: [0.15, 0.92], size: 24, weight: 'bold' }
    label_B: { text: 'SCUBA2 850$\mu$m ', relative: True,
                position: [0.17, 0.87], size: 20, color: 'blue' }
    label_C: { text: 'r1', relative: True, position: [0.17, 0.83],
                     size: 16, color: 'blue'} 

  
  colorbar:
    width: 0.20
    pad: 0.02
    label_text: 'S 850 (mJy/beam)'
  
  contours:
    colors: 'darkgreen'
    base: 8.124
    linewidth: 0.8

  pixrange:
    colormap: 'afmhot_r'
    base: 8.124
    range: [-3, 160, 'arcsinh']

  panel_01:
    axes:
      ticks: { xspacing: 0.083333, yspacing: 0.0833333,
               xminor_freq: 4, yminor_freq: 5, direction: in, 
               color: 'purple', length: 6, linewidth: 0.8,
               hide: False, xhide: False, yhide: False}
        

    labels:
      color: 'blue'
    #  label_6: { text: 'fw_01', relative: True, position: [0.17, 0.79],
    #                 size: 12, family: 'Nimbus Roman', }
                     
    dataset_01:
      filename: 'Sh2_61-j850r1.fits'
      dims: [0,1]
      type: 'pixel'

      beam:
        bmaj : '14.5499arcsec'
        corner : 'bottom right'
        frame: True
      
    dataset_02:
      filename: 'Sh2_61-j850r1.fits'
      dims: [0,1]
      type: 'cntr'
      
      contours:
        levels: [5,10,20,30,40,50,75,100,125,150]

      
