page:
  name: 'Sh2-61 j850r0_co_mb-cf_01-clumps'
  outfile: 'Sh2_61-j850r0_co_mb-cf_01-clumps-map.pdf'
  dpi: 150
  size: [9,9]

panels:
  yx: [1,1]
  view:
    type: 'radius'
    radius: '11arcmin'
    
  font: {family: 'Nimbus Roman'}

  axes:
    axes_labels:
      font: {size: 'xx-large'}

    tick_labels:
      font: {size: 'large'}
      
  labels:
    color: 'purple'
    label_A: { text: Sh2-61, relative: True,
               position: [0.15, 0.92], size: 24, weight: 'bold'}
    label_B: { text: 'SCUBA2 850$\mu$m', relative: True,
                position: [0.17, 0.87], size: 20, color: 'blue' }
    label_C: { text: 'r0 mb CO corr.', relative: True, position: [0.17, 0.83],
                     size: 16, color: 'blue'}
    label_AF: { text: 'AFGL 5502', relative: True, position: [0.45, 0.38],
                     size: 13, color: 'black', weight: 'bold' }
    label_AS: { text: 'AS 310', relative: True, position: [0.64, 0.56],
                     size: 13, color: 'black', weight: 'bold' }

  markers:
    marker-03: { file: '../../config/figures/markers_ir.dat',
                 linewidth: 1.25, show_label: False, type: '*',
                 facecolor: None, edgecolor: 'black', lpad: [-150,0],
                 color: 'black', weight: 'bold', size: 10}

    marker-04: { file: '../../config/figures/markers_ism.dat',
                 linewidth: 1.25, show_label: False, type: 's',
                 facecolor: 'black', edgecolor: 'black', lpad: [-150,0],
                 color: 'black', weight: 'bold', size: 10}

    marker-05: { file: '../../config/figures/markers_hii.dat',
                 linewidth: 1.25, show_label: False, type: 'o',
                 facecolor: 'blue', lpad: [-150,0],
                 color: 'black', weight: 'bold', size: 10}

    marker-rad: { file: '../../config/figures/markers_rad.dat',
                 linewidth: 1.25, show_label: False, type: 'D',
                 facecolor: None, edgecolor: 'purple', lpad: [-150,0],
                 color: 'black', weight: 'bold', size: 10}

    marker-06: { file: '../../config/figures/markers_emo.dat',
                 linewidth: 1.25, show_label: False, type: '^',
                 facecolor: None, edgecolor: 'mediumpurple', lpad: [-150,0],
                 color: 'black', weight: 'bold', size: 10}

    marker-cl: { file: '../findclumps/Sh2_61-j850r0_co_mb-cf_01-shapes.dat',
                 type: 'polygon', edgecolor: 'red', linewidth: 1.,
                 linestyle : 'dashed', show_label: True,
                 color: 'red', weight: 'bold', size: 12}

    marker-src: { file: '../../config/figures/markers_main.dat',
                 linewidth: 1.6, show_label: False, type: '(4,2,0)',
                 facecolor: 'dodgerblue', lpad: [-150,0],
                 color: 'black', weight: 'bold', size: 12}



  colorbar:
    width: 0.20
    pad: 0.02
    label_text: '$S_{850}$ (mJy beam$^{-1}$)'
    font: {size: 14} 
    label_font:  {size: 16}
  
  contours:
    colors: 'darkgreen'
    base: 2.048
    linewidth: 0.8

  pixrange:
    colormap: 'afmhot_r'
    base: 2.048
    range: [-3, 700, 'arcsinh']

  panel_01:
    axes:
      ticks: { xspacing: 0.083333, yspacing: 0.0833333,
               xminor_freq: 4, yminor_freq: 5, direction: in, 
               length: 6.5, linewidth: 0.9,
               hide: False, xhide: False, yhide: False}
        

    labels:
      color: 'red'
      label_6: { text: 'cf_01', relative: True, position: [0.17, 0.79],
                     size: 12, family: 'Nimbus Roman', }
                     
    dataset_01:
      filename: 'Sh2_61-j850r0_co_mb.fits'
      dims: [0,1]
      type: 'pixel'

      beam:
        bmaj : '17.5461arcsec'
        corner : 'bottom right'
        frame: True
      
    dataset_02:
      filename: 'Sh2_61-j850r0_co_mb.fits'
      dims: [0,1]
      type: 'cntr'
      
      contours:
        levels: [10,25,50,100,150,200,250,300,350,500,750,1000]

      
